### ISSUE TITLE
crash on start up program

### ISSUE THREAD

**Issue by Uly41** [uraymeiviar/chiagen#2]
Using win10
downloaded the 210615 version. It show the GUI window first time run.
Then I close the GUI window and crash every time when I reopen GUI(3 versions avx,av2,sse).
And still not work however restart my pc.

BTW what difference between these 3 version(avx avx2 sse)?

**Comment by uraymeiviar** [comment]
those are CPU instruction set, if you have AVX2 capable like ryzen or gen10+ intel, better use that, should be faster, others are for older CPU

can you try again with latest release, there are numerous fixes regarding crash caused by GUI

**Comment by SiegWahrheit** [comment]
Same problem here

**Comment by xandejs** [comment]
> Using win10
> downloaded the 210615 version. It show the GUI window first time run.
> Then I close the GUI window and crash every time when I reopen GUI(3 versions avx,av2,sse).
> And still not work however restart my pc.
> 
> BTW what difference between these 3 version(avx avx2 sse)?

Same problem here, it worked first time.

**Comment by Uly41** [comment]
> those are CPU instruction set, if you have AVX2 capable like ryzen or gen10+ intel, better use that, should be faster, others are for older CPU
> 
> can you try again with latest release, there are numerous fixes regarding crash caused by GUI

Updated ver 0616, still crash on launch on all cpu instruction versions.
Here is the launch screenshot and it will close immediately.
really want to use this tool, and thank you for developing.
![chiagen-error](https://user-images.githubusercontent.com/3700610/122141696-717bb300-ce80-11eb-867a-79025b800ea0.png)

**Comment by Uly41** [comment]
> > Using win10
> > downloaded the 210615 version. It show the GUI window first time run.
> > Then I close the GUI window and crash every time when I reopen GUI(3 versions avx,av2,sse).
> > And still not work however restart my pc.
> > BTW what difference between these 3 version(avx avx2 sse)?
> 
> Same problem here, it worked first time.

OK, I solved this problem by myself.
FYI, just delete the tmp directory %LocalAppData\uraymeiviar, and launch again will be worked.

**Comment by uraymeiviar** [comment]
> > > Using win10
> > > downloaded the 210615 version. It show the GUI window first time run.
> > > Then I close the GUI window and crash every time when I reopen GUI(3 versions avx,av2,sse).
> > > And still not work however restart my pc.
> > > BTW what difference between these 3 version(avx avx2 sse)?
> > 
> > 
> > Same problem here, it worked first time.
> 
> OK, I solved this problem by myself.
> FYI, just delete the tmp directory %LocalAppData\uraymeiviar, and launch again will be worked.

wow thx, i didn't know the ImGui writing config setting to that folder, i will remove these

**Comment by uraymeiviar** [comment]
fixed on 210617
